export { default as Footer } from './Footer'
export { default as Header1 } from './Header1'
export { default as Header2 } from './Header2'
export { default as Layout } from './Layout'
export { default as HeroComponent } from './HeroComponent'
