import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { HeroComponent } from '../src/components'

export async function getStaticProps(context) {
  return {
    props: {},
  }
}

export default function Home({}) {
  return (
    <div>
      <Head>
        <title>Al Rafaheia Rental</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <HeroComponent />
      </main>
    </div>
  )
}
